name: 'Inga'
description: 'Analysis for typescript'
inputs:
  base-commit:
    description: ''
  root-path:
    description: ''
  exclude:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base-commit }}
    - ${{ inputs.root-path }}
    - ${{ inputs.exclude }}
