name: 'Inga Analysis'
description: 'Visualize code changes and impact on users'
inputs:
  language:
    description: 'Languages to be analyzed. ("java" | "typescript")'
    required: true
  root-path:
    description: 'Relative path of the project to be analyzed, so if you do not give this option, it defaults to the command execute path.'
    default: '.'
  exclude:
    description: 'Filenames of glob pattern matching to exclude from analysis. (e.g. "**/*.test.(ts|tsx)")'
    default: ''
  report-base:
    description: 'Set the base path for the HTML report. Set `<REPO>` if using GitHub Pages and the URL is `https://<USERNAME>.github.io/<REPO>/`.'
    default: '/'
runs:
  using: 'composite'
  steps:
    - name: git diff
      id: diff
      run: git diff ${{ github.event.pull_request.base.sha }} --unified=0 --
      shell: bash
    - uses: seachicken/inga-action/java@report
      if: inputs.language == 'java'
      with:
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
        diff: ${{ steps.diff.outputs.stdout }}
    - uses: seachicken/inga-action/typescript@report
      if: inputs.language == 'typescript'
      with:
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
        diff: ${{ steps.diff.outputs.stdout }}
    - name: Checkout inga-ui
      uses: actions/checkout@v3
      with:
        repository: seachicken/inga-ui
        path: inga
    - name: Install dependencies
      working-directory: ./inga
      run: npm ci
      shell: bash
    - name: Report to PR comments
      working-directory: ./inga
      run: gh pr comment --body $(npm run print-pr --ingapath=${GITHUB_WORKSPACE}/reports/report.json --ingaurl=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} --ingasha=${{ github.event.pull_request.head.sha }}) --edit-last
      shell: bash
    - name: Build HTML reports
      working-directory: ./inga
      run: npm run build --ingapath=${GITHUB_WORKSPACE}/reports/report.json --ingaurl=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} --ingasha=${{ github.event.pull_request.head.sha }} -- --base=${{ inputs.report-base }}
      shell: bash
branding:
  icon: 'layers'
  color: 'green'
