name: 'Inga Analysis'
description: 'Visualize code changes and impact on users'
inputs:
  language:
    description: 'Languages to be analyzed. ("java" | "typescript")'
    required: true
  root-path:
    description: 'Relative path of the project to be analyzed, so if you do not give this option, it defaults to the command execute path.'
    default: '.'
  exclude:
    description: 'Filenames of glob pattern matching to exclude from analysis. (e.g. "**/*.test.(ts|tsx)")'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: seachicken/inga-action/java@fix-result
      if: inputs.language == 'java'
      with:
        base-commit: ${{ github.event.pull_request.base.sha }}
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
    - uses: seachicken/inga-action/typescript@main
      if: inputs.language == 'typescript'
      with:
        base-commit: ${{ github.event.pull_request.base.sha }}
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
    - uses: seachicken/inga-action/report@fix-result
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        type: html-report
        report-base: /${{ github.event.repository.name }}/
branding:
  icon: 'layers'
  color: 'green'
